version: 0.1

 phases:
   build:
     commands:
       - echo Nothing to do yet
artifacts:
   files:
     - index.html
     - favicon.ico
     - FEDORFILONOV_Resume
     - styles/main.css
     - images/*
